### ISSUE TITLE
DXRuby 1.4.6 does't work on Ruby 2.4~2.6 on Windows 10

### ISSUE THREAD

**Issue by noanoa07** [mirichi/dxruby#1]
DXRuby 1.4.6 can install on Ruby 2.4~2.6. But does't work correctly.

- Windows 10 Home (64bit) version 1809
- Ruby 2.4/ 2.5/ 2.6 (32bit: i386-mingw32) from RubyInstaller for Windows.

--------------
Here are the error messages;
```PowerShell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

> ruby -v
ruby 2.4.5p335 (2018-10-18 revision 65137) [i386-mingw32]

> gem install dxruby
Fetching: dxruby-1.4.6.gem (100%)
Successfully installed dxruby-1.4.6
Parsing documentation for dxruby-1.4.6
Installing ri documentation for dxruby-1.4.6
Done installing documentation for dxruby after 0 seconds
1 gem installed

> irb
irb(main):001:0> require 'dxruby'
LoadError: 126: 指定されたモジュールが見つかりません。   - C:/Ruby245-x86/lib/ruby/gems/2.4.0/gems/dxruby-1.4.6/lib/2.4/dxruby.so
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby245-x86/lib/ruby/gems/2.4.0/gems/dxruby-1.4.6/lib/dxruby.rb:2:in `<top (required)>'
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby245-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby245-x86/bin/irb.cmd:19:in `<main>'
```
--------------
```PowerShell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

> ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [i386-mingw32]

> gem install dxruby
Fetching: dxruby-1.4.6.gem (100%)
Successfully installed dxruby-1.4.6
Parsing documentation for dxruby-1.4.6
Installing ri documentation for dxruby-1.4.6
Done installing documentation for dxruby after 0 seconds
1 gem installed

> irb
irb(main):001:0> require 'dxruby'
Traceback (most recent call last):
        9: from C:/Ruby253-1-x86/bin/irb.cmd:19:in `<main>'
        8: from (irb):1
        7: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        6: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        5: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        4: from C:/Ruby253-1-x86/lib/ruby/gems/2.5.0/gems/dxruby-1.4.6/lib/dxruby.rb:2:in `<top (required)>'
        3: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        2: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        1: from C:/Ruby253-1-x86/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
LoadError (126: 指定されたモジュールが見つかりません。   - C:/Ruby253-1-x86/lib/ruby/gems/2.5.0/gems/dxruby-1.4.6/lib/2.5/dxruby.so)
```
(Almost same on Ruby 2.6)

**Comment by noanoa07** [comment]
This is because the lack of d3dx9_40.dll on Windows 10.
(thanks [@nodai2hITC](https://twitter.com/nodai2hITC/status/1098957212330803202) !)

See below;
- [Fix/ d3dx9_40.dll is missing or not designed to run on Windows - Appuals.com](https://appuals.com/fix-d3dx9_40-dll-is-missing-or-not-designed-to-run-on-windows/)


- [d3dx9_40.dllがないため -A列車でいこう9を買ったのですが最初に - 教えて!goo](https://oshiete.goo.ne.jp/qa/9104931.html)

-------------------------------
**やり方；**
d3dx9_40.dllは、公式のMicrosoftのサイトからダウンロードするのが安全。

1. DirectX End-User Runtimes(June 2010)をダウンロードする。
https://www.microsoft.com/en-us/download/details.aspx?id=8109

2. ダウンロードした directx_Jun2010_redist.exe  をダブルクリック。
適当なフォルダを指定して、解凍する。

3. 解凍先のフォルダに DXSETUP.exe があり、ダブルクリックするとDirectX をインストールできるのでそれでもよいが、必要なのは d3dx9_40.dllだけなので、今回はこれのみを使うことにする。

4. 必要なのは32bit版の d3dx9_40.dllなので、Nov2008_d3dx9_40_x86.cabをダブルクリックする。

5. 中の d3dx9_40.dllをダブルクリックして、適当なフォルダを指定して解凍する。

6. 解凍先のフォルダに d3dx9_40.dllができる。

7. C:\Windows\SysWOW64フォルダ（こちらが32bit用プログラムフォルダ）
にコピーする。

> 対象のフォルダーへのアクセスは拒否されました
> SysWOW64
> このフォルダーへコピーするには管理者の権限が必要です

とパネルが出るので

`続行`

を押すとコピーされる。

8. Windows を再起動する。

**Comment by nodai2hITC** [comment]
DirectX Runtimes をちゃんとインストールしないといけないと思っていましたが、d3dx9_40.dll だけを公式インストーラから取り出すことができるんですね。参考になりました。
とりあえず DXRuby さえ動けばいいなら、C:\Windows\SysWOW64 フォルダでなくても、Ruby の bin フォルダに d3dx9_40.dll をコピーするのでも大丈夫そうです。

**Comment by mirichi** [comment]
Windows10で確認できておらず、すみませんでした。ありがとうございます。
